title: Ubitus Wiki
description: Documentation about the Ubitus protocols
theme: just-the-docs
color_scheme: dark

url: https://pandorastream.github.io

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
